### ISSUE TITLE
Archive appears to be down

### ISSUE THREAD

**Issue by pojntfx** [minos-org/minos-static#19]
As of right now, trying to get any package appears to fail:

```bash
% ./static-get tmux
no available packages at s.minos.io/archive, it may be an incorrect url or could be down temporarily
```

It appears that the archive is currently down.

**Comment by javier-lopez** [comment]
Hello, @pojntfx, indeed that is the case, I'm doing some maintainance work, it should be back online in less than 24 hrs, sorry for the inconvenience.

**Comment by pojntfx** [comment]
@javier-lopez Absolutely no problem, I'll be sure to check back in time. Thanks so much for your work!

**Comment by javier-lopez** [comment]
Maintenance is over, the archive should be back online, before reporting any issue please update the static-get script:

`$ sudo static-get -U`

**Comment by pojntfx** [comment]
I’ve just checked it, everything is back to normal. Thanks!
