### ISSUE TITLE
Archive down?

### ISSUE THREAD

**Issue by climbTheStairs** [minos-org/minos-static#29]
After cloning this repo and running `./static-get gcc`, I receive the error message:

```no available packages at s.minos.io/archive, it may be an incorrect url or could be down temporarily```

However, I am still able to access <http://s.minos.io/archive/> regularly with my browser.

Am I doing something wrong?  Are there any installation steps I must do before running the script?

**Comment by javier-lopez** [comment]
hello, can you run the above command in debugging mode?, `$ bash -x static-get gcc`

**Comment by climbTheStairs** [comment]
I ran that command, and it still outputted the same error.

However, I discovered that it was because I did not have wget installed, and the script doesn't work with curl.  See my pull request.

**Comment by javier-lopez** [comment]
awesome, thank you for the typo fix!, 🍻
