### ISSUE TITLE
Deprecated protocol git://

### ISSUE THREAD

**Issue by adriangrigore** [minos-org/minos-static#32]
Running 

    sudo ./bifrost-autobuild init

gives

      The unauthenticated git protocol on port 9418 is no longer supported.
    Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
    
I recommend switching to `https` protocol.

**Comment by javier-lopez** [comment]
Hello Adrian,

Thank for the notification, I've replaced git: with https: in the affected scripts in https://github.com/minos-org/minos-static/commit/2f1adeb1eb7514b865712f3ff88082a1031462f7, closing ticket, 🍻
