### ISSUE TITLE
[+] ALT Project: https://github.com/Azathothas/Toolpacks

### ISSUE THREAD

**Issue by Azathothas** [minos-org/minos-static#36]
Hello, first, I would like to apologize for shilling my own project here.
Please feel free to delete this issue if it's not acceptable.

I loved this project, and it was one of several inspirations to start my own.
Unfortunately, it seems like this project was abandoned `Last commit 2 Years ago` which is completely understandable.
Hopefully, this serves as a potential replacement/alternative to people.

To everyone else:
> - I have a similar, much more ambitious project at: https://github.com/Azathothas/Toolpacks
> - There's already over [`2000+` precompiled binaries](https://bin.ajam.dev/) available to download, and all of them also come with a `.upx` packed versions.
> - Check my project out, and help me (& others) by [contributing](https://github.com/Azathothas/Toolpacks/tree/main/Docs#how-to-contribute)/[reporting Issues](https://github.com/Azathothas/Toolpacks/issues) there.

Thanks !

**Comment by javier-lopez** [comment]
Hello, not an issue, on the contrary, it's nice to read there exists alternatives, unfortunatelly I do not have enough free time to maintain this project, the current built recipes are still available and will be in the near future but unless someone pops up and update the core built scripts it probably eventually would just fade out, I'll point out to your project on the readme so more people are aware of it, 🍻

**Comment by Azathothas** [comment]
Thank you so much!
I really appreciate the shoutout.
