### ISSUE TITLE
nano not worked in docker container. Thanks.

### ISSUE THREAD

**Issue by zw963** [minos-org/minos-static#5]
nano not worked for me in docker container, I have report this issue in your's blog too.

Following is some info:

# ls /lib/terminfo/
E  a  c  d  h  l  m  p	r  s  v  w  x

#  export TERMINFO=/lib/terminfo

# echo $TERM
dumb

# nano
Error opening terminal: unknown.

Thanks.

# cat /etc/issue
Debian GNU/Linux 8 \n \l

**Comment by javier-lopez** [comment]
That's a known docker issue: https://github.com/docker/docker/issues/8631 , try setting TERM to a valid terminal, eg $ export TERM=xterm and relaunch nano

**Comment by zw963** [comment]
> try setting TERM to a valid terminal, eg $ export TERM=xterm and retry launching nano

Worked! thanks.
